services:
  db:
    image: postgres:9
    ports:
      - "9999:5432"
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: visionaryDb
    volumes:
      - ./data/database:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 7770:8080
    depends_on:
      - db
