services:
  db:
    image: postgres:9
    ports:
      - "9999:5432"
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: visionaryDb
    volumes:
      - ./data/database:/var/lib/postgresql/data
#  db:
#    image: mysql:8.0.0
#    ports:
#      - "9999:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: visionaryDb
#    volumes:
#      - ./data/mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 7770:8080
    depends_on:
      - db
